# Generated by Django 5.2.8 on 2026-01-04 16:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xsell_shb', models.BooleanField(default=False, verbose_name='Xsell SHB')),
                ('disbursement_date', models.DateField(blank=True, null=True, verbose_name='Ngày giải ngân')),
                ('name', models.CharField(max_length=100, verbose_name='Họ tên')),
                ('phone', models.CharField(max_length=20, verbose_name='Số điện thoại')),
                ('cccd', models.CharField(max_length=20, verbose_name='CCCD')),
                ('address', models.CharField(max_length=255, verbose_name='Nơi ở')),
                ('province', models.CharField(max_length=100, verbose_name='Tỉnh')),
                ('bad_debt', models.BooleanField(default=False, verbose_name='Nợ xấu')),
                ('late_payment', models.BooleanField(default=False, verbose_name='Trả chậm')),
                ('company', models.CharField(blank=True, max_length=255, verbose_name='Công ty')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Ngày nhập')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('sales', models.ManyToManyField(blank=True, related_name='customers', to=settings.AUTH_USER_MODEL, verbose_name='Sale phụ trách')),
            ],
        ),
    ]
