# Generated by Django 5.2.8 on 2026-01-04 16:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_customer_bad_debt_year_customer_late_payment_year'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='sales',
            field=models.ManyToManyField(blank=True, related_name='customers', to=settings.AUTH_USER_MODEL),
        ),
    ]
