# Generated by Django 5.2.8 on 2026-01-05 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_remove_customer_address_customer_notified_6m_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cccd',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='province',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
